version: '3'
services:
  jms-gateway:
    image: reinkrul/jms-gateway:latest
    restart: always
    environment:
      JMS_URL: tcp://jms-broker:61616
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://database:5432/postgres
      JDBC_USER: postgres
      JDBC_PASSWORD: postgres
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
  jms-broker:
    image: vromero/activemq-artemis:2.6.2-alpine
    volumes:
      - ./artemis-config/broker-00.xml:/var/lib/artemis/etc-override/broker-00.xml:ro
  database:
    image: postgres:10.4
    healthcheck:
      test: ["CMD", "pg_isready"]
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./../src/main/resources/database:/docker-entrypoint-initdb.d:ro