spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_URL}
    driver-class-name: ${JDBC_DRIVER}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    schema:
    hikari:
      idle-timeout: 10000

jms:
  provider: ${JMS_PROVIDER:artemis}
  url: ${JMS_URL}
  authentication:
    user: artemis
    password: simetraehcapa